_core:
  default_config_hash: WKPJoaS0nZiIboNwD58sBSpxmtib3XbeyMWgbExqsnE
url_with_class: "/services|services-page\r\n/company|company-page\r\n/company/career|career-page\r\n/properties|properties-page\r\n/news|news-page\r\n/neighborhoods|neighborhoods-page\r\n/<front>|home-page\r\n/properties/sale|property-sale-page\r\n/properties/rent|property-rent-page"
