_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
smtp_on: false
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: mreproject.v3@gmail.com
smtp_password: ''
smtp_from: mreproject.v3@gmail.com
smtp_fromname: 'Marks Real Estate'
smtp_client_hostname: smtp.gmail.com
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: true
